### ISSUE TITLE
Is a description for each x-enumNames value supported?

### ISSUE THREAD

**Issue by stevenvolckaert** [RicoSuter/NJsonSchema#1156]
I'm writing an OpenAPI 3 spec for an API that we want to integrate with. We then use the NSwag toolchain (NSwag.MSBuild) to generate C# clients based on the hand-writtten OpenAPI spec.

In the spec, I've defined the following model:

``` yaml
components:
  schemas:
    AutomationStatus:
      description: Represents the status of an automation.
      enum:
      - 0
      - 1
      - 2
      type: integer
      x-enumNames:
      - None
      - Active
      - Completed
```

As expected, this generates:

``` csharp
    /// <summary>Represents the status of an automation.</summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.1.11.0 (Newtonsoft.Json v12.0.0.0)")]
    public enum AutomationStatus
    {
        None = 0,
    
        Active = 1,
    
        Completed = 2,
    
    }
```

Is it possible somehow to have NSwag generate a `<summary>` element for each enum value? Is this supported?
