### ISSUE TITLE
C# code gen enums: descriptions + open-endedness

### ISSUE THREAD

**Issue by adamjones1** [RicoSuter/NJsonSchema#1159]
There are two scenarios with enums in specs which are not supported (both elaborated on in [this thread](https://github.com/OAI/OpenAPI-Specification/issues/1552)):

### Enums with item descriptions
According to one of the JSON Schema maintainers, the standard pattern for this is by wrapping each case in a singleton type with a description, ie like:

```
myEnum:
  type: int
  oneOf:
    - enum: [1]
      title: Foo
    - enum: [2]
      title: Bar
      description: This is a bar
```
to translate to
```
enum MyEnum
{
    Foo = 1,
    /// <summary>This is a bar</summary>
    Bar = 2
}
```

### Open-ended/extensible enums
The pattern for this as described on the thread is allegedly:

```
myEnum:
  type: string
  - anyOf:
    - enum:
      - foo
      - bar
    - {}
```
to translate, I guess, to
```
enum MyEnum
{
    Foo,
    Bar,
    _Other
}
```
or perhaps just as a vanilla `string` together with the generation of a class like
```
static class MyEnum
{
    public const string Foo = "foo";
    public const string Bar = "bar";
}
```

I propose that both of these patterns, and their combination (as I described on the referenced thread), are detected and supported.
