### ISSUE TITLE
in openApiToCSharpClient, react to dateTime-format

### ISSUE THREAD

**Issue by Debbus72** [RicoSuter/NJsonSchema#1274]
We use the openApiToCSharpClient to generate our models. We now have the need to add an attribute on generated date-time properties:
```yaml
      type: object
      properties:
        estimatedLoadingDateTime:
          type: string
          format: date-time
```
I tried to change the .liquid files, but there is no property in the PropertyModel to access either whether it is a DateTime (There is a property called `IsDate` but no `IsDateTime`), neither is a way to access the original content of the `format` property.
