### ISSUE TITLE
Integers without formats don't generate default negative values in code

### ISSUE THREAD

**Issue by sr185400** [RicoSuter/NJsonSchema#1420]
Given the following YAML spec:
```
exampleproperty:
  type: integer
  default: -1
```
The default value is missing in code/controller generation unless an explicit format is given as such:
```
exampleproperty:
  type: integer
  format: int32
  default: -1

```
