### ISSUE TITLE
Multiline comments generation issue

### ISSUE THREAD

**Issue by vadimi** [RicoSuter/NJsonSchema#1462]
Hello, after PR #1346 code generation for multiline comments produces invalid `<summary>` xml doc.

For example:

```yaml
    TestType:
      type: object
      properties:
        code:
          type: string
          description: |
            * test1
            * test2
```

produces the following c# code:

```csharp
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.15.3.0 (NJsonSchema v10.6.4.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class TestType
    {
        /// <summary>* test1
        /// <br/>* test2
    </summary>
        [Newtonsoft.Json.JsonProperty("code", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Code { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties = new System.Collections.Generic.Dictionary<string, object>();

        [Newtonsoft.Json.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties; }
            set { _additionalProperties = value; }
        }

    }
```

As you see the closing `</summary>` tag doesn't start with `///` which breaks the compilation
