### ISSUE TITLE
Custom Type Resolver

### ISSUE THREAD

**Issue by csehatt741** [RicoSuter/NJsonSchema#1507]
I'd like to generate `System.Version` for the following schema:

```yaml
schema:
  type: string
  format: version
```

Generator: CSharpGenerator
NSwag version: 13.15.10.0

Based on my current understanding, `CSharpTypeResolver.ResolveString` is responsible for such type resolution, but I cannot figure out the way to extend this functionality or specify a custom type resolver.
