### ISSUE TITLE
TypeScript generation with EnumStyle `StringLiteral` and defaults

### ISSUE THREAD

**Issue by nycdotnet** [RicoSuter/NJsonSchema#1618]
I am generating TypeScript code for an API with a MyClass schema defined like this:

```yaml
myProperty:
  type: "string"
  enum:
  - "ABC"
  - "DEF"
  - "GHI"
      default: "ABC"
```

I am generating with `/enumStyle:StringLiteral`.  This will correctly generate the type for myProperty which looks like this:

```typescript
export type MyClassMyProperty = "ABC" | "DEF" | "GHI";
```

However, when the default is used within the `init` method of `MyClass`, it still tries to use enum syntax which gives an error:

```typescript
this.myProperty= _data["myProperty"] !== undefined ? _data["myProperty"] : MyClassMyProperty.ABC;
```

I think this was just an oversight during the implementation of #1137 .  I am going to attempt to address this.
